language: node_js
sudo: required
services:
  - docker

before_install:
  #build docker image (tag name is just a convention- can be anything really)
  - docker build -t 155663/docker-react -f Dockerfile.dev .

script:
  - docker run 155663/docker-react npm run test -- --coverage
  #the commands to be executed to actually run our test suite
  #to avoid npm run test to hang for input we add '-- --coverage'